modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "icon.png"
description = '''${mod_description}'''

# Mixin 配置在 NeoForge(1.20.5+) 里由这里声明，不再走 manifest 的 MixinConfigs
[[mixins]]
config = "gregnuovo.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtceu"
type = "required"
versionRange = "[7.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
type = "required"
versionRange = "[19.2.0,)"
ordering = "AFTER"
side = "BOTH"
